### ISSUE TITLE
How to change Validity ?

### ISSUE THREAD

**Issue by rafaelbassora** [shubanker/DynamicFieldsNames#1]
How i can change the value for a 2 hours?

$defaultKeyValidity="120 mins";

or 

$defaultKeyValidity="2 hours";

?

Great Class man! Thanks

**Comment by shubanker** [comment]
Both `"2 hours"` and `"120 mins"` should give same result however you may not need to modify default value, you can pass on expiry while creating instance of class.

`DynamicForms` constructor accepts `keyValadity` as 3rd argument, you can pass on that to  that.
https://github.com/shubanker/DynamicFields/blob/a2158ca4859ac1db11d9b836325eb0b2c3fedba5/DynamicForms.php#L28

something like
```PHP
$dynamicFields=new DynamicForms(false,false,"2 hours");
```

**Comment by rafaelbassora** [comment]
Thanks for lot!, I think too,  (if as possible of course....) Create an method to unset the fields after the submit, to prevent brute force attacks.

**Comment by shubanker** [comment]
Reset is available already
`resetKeys()`

Usage:
```php
$dynamicFields.resetKeys();
```

**Comment by rafaelbassora** [comment]
Thanks
